In [ ]:
 #3.1(a) to get help on the add() function
 import numpy as np
 print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [ ]:
#3.1(b) To test whether none of the elements of a given array is zero
import numpy as np
arr=np.array([1,2,3,4])
print("\nAll elements are non-zero:",np.all(arr))
print(np.info(np.all))


All elements are non-zero: True
Test whether all array elements along a given axis evaluate to True.

Parameters
----------
a : array_like
    Input array or object that can be converted to an array.
axis : None or int or tuple of ints, optional
    Axis or axes along which a logical AND reduction is performed.
    The default (``axis=None``) is to perform a logical AND over all
    the dimensions of the input array. `axis` may be negative, in
    which case it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, a reduction is performed on multiple
    axes, instead of a single axis or all the axes as before.
out : ndarray, optional
    Alternate output array in which to place the result.
    It must have the same shape as the expected output and its
    type is preserved (e.g., if ``dtype(out)`` is float, the result
    will consist of 0.0's and 1.0's). See :ref:`ufuncs-output-type`
    for more details.

keepdims : bool, optional
   

In [ ]:
#3.1(c) To create an element-wise comparison(greater, graeter equal,less,lesss equal, equal, equal withih a tolerance)
#greater
a=np.array([10,20,30])
b=np.array([15,20,25])
print("Greater:",np.greater(a,b))
print("Greater Equal:",np.greater_equal(a,b))
print("Less:",np.less(a,b))
print("Less Equal:",np.less_equal(a,b))
print("Equal:",np.equal(a,b))

#Check if array are almost equal(within a tolerance)
c=np.array([1.0001,2.0001])
d=np.array([1.0002,2.0002])
print("Allclose:",np.allclose(c,d))   #True(within default tolerance)

Greater: [False False  True]
Greater Equal: [False  True  True]
Less: [ True False False]
Less Equal: [ True  True False]
Equal: [False  True False]
Allclose: False


In [ ]:
# ex:Zeroes
import numpy as np
print("/nZeroes:",np.zeros((3,2)))
#ones
print("Ones:",np.ones((2,3)))
#linspace
print("Linspace:",np.linspace(100,1500,8))
#tolist
print("Convert array to list:",a.tolist())
r=0
print(r*100)

/nZeroes: [[0. 0.]
 [0. 0.]
 [0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]
Linspace: [ 100.  300.  500.  700.  900. 1100. 1300. 1500.]
Convert array to list: [10, 20, 30]
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000  


In [ ]:
#3.2(a) Numpy Program using Methods
import numpy as np
arr=np.array([10, 40, 5, 50])
print("Greater than 20:",arr[arr>20])
print(arr)
print("Less than 30:",arr[arr<20])
print(arr)

Greater than 20: [40 50]
[10 40  5 50]
Less than 30: [10  5]
[10 40  5 50]


In [ ]:
#3.2(b)Find indices of max and min numbers along a given axis
arr2d=np.array([[10,20,30],[5,25,40]])

#Index of max,min along axis 0 (column-wise)
print("Argmax(axis=0):",np.argmax(arr2d,axis=0))
print("Argmin(axis=0):",np.argmin(arr2d,axis=0))

#Index of max,min along axis 1 (row-wise)
print("Argmax(axis=1):",np.argmax(arr2d,axis=1))
print("Argmin(axis=1):",np.argmin(arr2d,axis=1))

arr3d=np.array([[10,20,30],[5,25,40],[30,5,15]])
#Index of max,min along axis 0 (column-wise)
print("Argmax(axis=0):",np.argmax(arr3d,axis=0))
print("Argmin(axis=0):",np.argmin(arr3d,axis=0))

#Index of max,min along axis 1 (row-wise)
print("Argmax(axis=1):",np.argmax(arr3d,axis=1))
print("Argmin(axis=1):",np.argmin(arr3d,axis=1))

Argmax(axis=0): [0 1 1]
Argmin(axis=0): [1 0 0]
Argmax(axis=1): [2 2]
Argmin(axis=1): [0 0]
Argmax(axis=0): [2 1 1]
Argmin(axis=0): [1 2 2]
Argmax(axis=1): [2 2 0]
Argmin(axis=1): [0 0 1]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print()
arr=np.array([[[1,2,3],[4,5,6]],[[4,5,6],[7,8,9]]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]
